<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <LangVersion>11.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Data\Data.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Server" Version="1.0.26803" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
