<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-DiscordBot-77784c2d-a3a9-4f93-8ae8-7072e656401b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.19.1" />
    <PackageReference Include="Discord.Net.Interactions" Version="3.19.1" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
    <Folder Include="images\" />
    <Folder Include="Embed\" />
  </ItemGroup>
</Project>
